### ISSUE TITLE
HW01 document

### ISSUE THREAD

**Issue by Taeyoung96** [mqjinwon/ComputerVision#1]
Thanks for your great work!  

You can change doc files to pdf files, you could upload to this repository!  

I hope these comments help.  :tada:

**Comment by mqjinwon** [comment]
> Thanks for your great work!
> 
> You can change doc files to pdf files, you could upload to this repository!
> 
> I hope these comments help.

Oh, I see! I checked it now from Gmail.
I'll change it later :)
